[db_server]
db_server_phonebook ansible_host=44.222.85.252

[blue_servers]
blue_server_phonebook ansible_host=98.84.23.39

[green_servers]
green_server_phonebook ansible_host=34.229.64.209

[web_servers:children]
blue_servers
green_servers

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/RefiaKeyPair.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
